#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/My_Robota_awk.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar:$APPDIR/lib/SimpleOpenNI.jar" My_Robota_awk
